### ISSUE TITLE
SMSs are stuck in PENDING state after being successfully sent

### ISSUE THREAD

**Issue by dianabarsan** [medic/medic-gateway#154]
# Device(s) tested

key | value(s)
---|---
medic-gateway version | master
device make | LG
device model | Nexus 5x - Android 8.1
can the problem be recreated on this device? | yes

# Observed behaviour

All SMSs that Gateway sends are stuck in "PENDING" status after being sent successfully.

# Expected behaviour

SMSs should change the status to SENT or DELIVERED after being successfully send and/or delivered to the target.

# Steps to recreate

Have Gateway send an SMS. Observe the SMS is received by the target. Gateway reports SMS as "PENDING".

relevant logs:

```
D MedicGateway: medic.gateway.alert.Db :: getWoMessages() :: item fetch count: 1
I MedicGateway: Sending 1 SMSs...
D MedicGateway: medic.gateway.alert.SmsSender :: sendUnsentSmses() :: attempting to send WoMessage@2586ba7d-8857-4713-839f-8843ce0b3f09-UNSENT
I MedicGateway: sendSms() :: [***********] 'a message'
D MedicGateway: medic.gateway.alert.Db :: updateStatus() :: WoMessage@2586ba7d-8857-4713-839f-8843ce0b3f09-UNSENT :: UNSENT -> PENDING (null)
D MmsService: getAutoPersisting
W BroadcastQueue: Background execution not allowed: receiving Intent { act=medic.gateway.alert.SENDING_REPORT flg=0x10 (has extras) } to medic.gateway.alert.generic/medic.gateway.alert.IntentProcessor
W BroadcastQueue: Background execution not allowed: receiving Intent { act=medic.gateway.alert.DELIVERY_REPORT flg=0x10 (has extras) } to medic.gateway.alert.generic/medic.gateway.alert.IntentProcessor
D WificondControl: Scan result ready event
D MedicGateway: medic.gateway.alert.Db :: getWtMessages() :: item fetch count: 0
MedicGateway: medic.gateway.alert.Db :: getWoMessageStatusUpdates() :: item fetch count: 1
D MedicGateway: medic.gateway.alert.SettingsStore :: loading for context: medic.gateway.alert.WakefulService@9e25ab3
D MedicGateway: medic.gateway.alert.Settings :: Settings() webappUrl=https://gateway:****@7715c5ab.eu.ngrok.io/api/sms
```

The important bit being:
```
W BroadcastQueue: Background execution not allowed: receiving Intent { act=medic.gateway.alert.SENDING_REPORT flg=0x10 (has extras) } to medic.gateway.alert.generic/medic.gateway.alert.IntentProcessor
W BroadcastQueue: Background execution not allowed: receiving Intent { act=medic.gateway.alert.DELIVERY_REPORT flg=0x10 (has extras) } to medic.gateway.alert.generic/medic.gateway.alert.IntentProcessor
```

I tried lowering the `compileSdkVersion` and `targetSdkVersion` and `buildToolsVersion` to 28. No change when tested.

**Comment by dianabarsan** [comment]
Just tested on another device where the SMSs go get the correct DELIVERED state:

key | value(s)
---|---
medic-gateway version | master
device make | HTC
device model | ONE - Android 5
can the problem be recreated on this device? | no

**Comment by benkags** [comment]
This is happening in Samsung A50 and Infinix Hot 8 devices. Messages' status never change to 'Delivered' or 'Sent'.

v1.5.0 apk shared by @henokgetachew [here](https://medic.slack.com/files/U02E2018U/FGHQ3H5SM/medicgateway1.5.0.apk?origin_team=T024KS27X&origin_channel=GV4QPTQLF) does not have this problem.

**Comment by garethbowen** [comment]
Deferring this to 3.10.0 so we can get 3.9.0 out as soon as possible - please contact me if you consider this more urgent.

The workaround as I understand it is to use an older android or an older apk.

This can be developed and released separately to the rest of cht-core.

**Comment by garethbowen** [comment]
Moved to 3.11.0 to align with other gateway work.

**Comment by latin-panda** [comment]
**Research:** 
Android Oreo (8+) added restrictions to background process to optimise memory usage. Must intents should be explicit.

In this repository means:
1. Remove the custom intent actions from the manifest, since they aren't going to be implicit anymore.
2. Create the Pending Intent and specify the context where it's associated to..
3. Set the custom action type (from # 1) in the Pending Intent object.

**More info here:**
[Broadcast limitations](https://developer.android.com/about/versions/oreo/background.html#broadcasts)
[Background optimizations](https://developer.android.com/topic/performance/background-optimization)
[Possible fix](https://stackoverflow.com/questions/53015975/static-broadcastreceiver-not-receiving-custom-intent)
https://commonsware.com/blog/2017/04/11/android-o-implicit-broadcast-ban.html

**Comment by latin-panda** [comment]
Regarding the second issue: Where sending multiple SMS on PENDING status, only one get updated to SENT.
Looks like this is because the [Pending Intent's broadcast](https://developer.android.com/reference/android/app/PendingIntent#getBroadcast(android.content.Context,%20int,%20android.content.Intent,%20int)) has the same `requestCode`, this parameter is use later to identify what SMS changed when the intent is fired. So it was being overrode.

**Comment by newtewt** [comment]
We have tested this using the branch and built to my android 11 device. Seeing the messages go from UNSENT -> PENDING ->SENT. The text then sends to my phone. 

The struggle we have is that none of QA's have a less than android 8 phone with service and I feel we should probably involve the tech leads to use a "beta" build of the gateway app to see if any issues are found with a prod instance.

**Comment by latin-panda** [comment]
Awesome, thanks @newtewt ! I support your idea of involving the tech leads to use the "beta", the Gateway is tricky to test with so many differences between phones and environments :)

**Comment by newtewt** [comment]
I believe this is ready to be merged after our group session we had for testing. Any objections @brad1905  @ngaruko ?

**Comment by brad1905** [comment]
Agreed, no objections
